# Generated by Django 5.1.7 on 2025-03-25 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField()),
                ('outside_Europe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('S', 'Small balloon'), ('M', 'Medium balloon'), ('L', 'Large balloon')], max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('max_passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('year_born', models.IntegerField()),
                ('total_flight_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.CharField(choices=[('J', 'Junior'), ('I', 'Intermediate'), ('S', 'Senior')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('airport_take_off', models.CharField(max_length=100)),
                ('airport_landing', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flight_images/')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.airline')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.balloon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='PilotAirLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.pilot')),
            ],
        ),
    ]
